apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world--ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world-ui
  template:
    metadata:
      labels:
        app: hello-world-ui
    spec:
      containers:
      - image: nginx:latest
        name: hello-world-ui
        ports:
        - containerPort: 80
